user_pref("app.donation.eoy.version.viewed", 5);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1727247932);
user_pref("app.update.lastUpdateTime.background-update-timer", 1727247932);
user_pref("app.update.lastUpdateTime.region-update-timer", 1727247932);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1727247932);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1720685633);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1727247932);
user_pref("browser.region.update.updated", 1727247933);
user_pref("browser.search.region", "ES");
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("calendar.caldav.googleResync", 1720685594);
user_pref("calendar.list.sortOrder", "e0a7a91f-54b0-4b0e-960c-88a096b1f45c");
user_pref("calendar.registry.e0a7a91f-54b0-4b0e-960c-88a096b1f45c.calendar-main-default", true);
user_pref("calendar.registry.e0a7a91f-54b0-4b0e-960c-88a096b1f45c.calendar-main-in-composite", true);
user_pref("calendar.registry.e0a7a91f-54b0-4b0e-960c-88a096b1f45c.disabled", true);
user_pref("calendar.registry.e0a7a91f-54b0-4b0e-960c-88a096b1f45c.name", "Casa");
user_pref("calendar.registry.e0a7a91f-54b0-4b0e-960c-88a096b1f45c.type", "storage");
user_pref("calendar.registry.e0a7a91f-54b0-4b0e-960c-88a096b1f45c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Madrid");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1720685591561");
user_pref("dom.events.asyncClipboard.clipboardItem", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.cardbook.optionsMigrated", true);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1727247933);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240903191356");
user_pref("extensions.lastAppVersion", "115.15.0");
user_pref("extensions.lastPlatformVersion", "115.15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.cardbook@vigneau.philippe", true);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"78836711-fb3e-4d77-b148-8ca7c4b3411c\",\"google@search.mozilla.org\":\"ec478284-4c81-4639-817b-1c3586d8c6ac\",\"ddg@search.mozilla.org\":\"8a90093d-fd82-456c-ac75-f4b0f2c57454\",\"wikipedia@search.mozilla.org\":\"d6443c4b-677d-4a1c-99e2-63ed2293d9c9\",\"bing@search.mozilla.org\":\"ec2b9afb-7f0e-4684-9af4-795dece9bd72\",\"drae@search.mozilla.org\":\"53142c1f-496f-4ca8-8f69-c59a76ff978a\",\"cardbook@vigneau.philippe\":\"82596cbf-bf2b-4a8f-943e-3ca053d41e54\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1727248368);
user_pref("ldap_2.servers.osx.uid", "d975923b-9839-4f9d-8762-869ac83e4959");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.account3.identities", "id2");
user_pref("mail.account.account3.server", "server3");
user_pref("mail.account.lastKey", 3);
user_pref("mail.accountmanager.accounts", "account1,account3,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server2");
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id1.archive_folder", "imap://ijazappa%40gmail.com@imap.gmail.com/[Gmail]/Todos");
user_pref("mail.identity.id1.archives_folder_picker_mode", "1");
user_pref("mail.identity.id1.attachPgpKey", true);
user_pref("mail.identity.id1.autoEncryptDrafts", true);
user_pref("mail.identity.id1.doBcc", false);
user_pref("mail.identity.id1.draft_folder", "imap://ijazappa%40gmail.com@imap.gmail.com/[Gmail]/Borradores");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "1");
user_pref("mail.identity.id1.e2etechpref", 0);
user_pref("mail.identity.id1.encryptionpolicy", 0);
user_pref("mail.identity.id1.fcc_folder", "imap://ijazappa%40gmail.com@imap.gmail.com/[Gmail]/Enviados");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "1");
user_pref("mail.identity.id1.fullName", "Ismael Jara");
user_pref("mail.identity.id1.is_gnupg_key_id", true);
user_pref("mail.identity.id1.protectSubject", true);
user_pref("mail.identity.id1.reply_on_top", 1);
user_pref("mail.identity.id1.sendAutocryptHeaders", true);
user_pref("mail.identity.id1.sign_mail", false);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.stationery_folder", "imap://ijazappa%40gmail.com@imap.gmail.com/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "ijazappa@gmail.com");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id2.archive_folder", "imap://jajz1061%40gmail.com@imap.gmail.com/[Gmail]/Todos");
user_pref("mail.identity.id2.archives_folder_picker_mode", "1");
user_pref("mail.identity.id2.attachPgpKey", true);
user_pref("mail.identity.id2.autoEncryptDrafts", true);
user_pref("mail.identity.id2.draft_folder", "imap://jajz1061%40gmail.com@imap.gmail.com/[Gmail]/Borradores");
user_pref("mail.identity.id2.drafts_folder_picker_mode", "1");
user_pref("mail.identity.id2.e2etechpref", 0);
user_pref("mail.identity.id2.encryptionpolicy", 0);
user_pref("mail.identity.id2.fcc_folder", "imap://jajz1061%40gmail.com@imap.gmail.com/[Gmail]/Enviados");
user_pref("mail.identity.id2.fcc_folder_picker_mode", "1");
user_pref("mail.identity.id2.fullName", "Ismael Jara");
user_pref("mail.identity.id2.is_gnupg_key_id", true);
user_pref("mail.identity.id2.protectSubject", true);
user_pref("mail.identity.id2.reply_on_top", 1);
user_pref("mail.identity.id2.sendAutocryptHeaders", true);
user_pref("mail.identity.id2.sig_bottom", true);
user_pref("mail.identity.id2.sign_mail", false);
user_pref("mail.identity.id2.smtpServer", "smtp2");
user_pref("mail.identity.id2.stationery_folder", "imap://jajz1061%40gmail.com@imap.gmail.com/Templates");
user_pref("mail.identity.id2.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id2.useremail", "jajz1061@gmail.com");
user_pref("mail.identity.id2.valid", true);
user_pref("mail.imap.chunk_size", 81920);
user_pref("mail.imap.min_chunk_size_threshold", 122880);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.purge_threshhold_mb", 20);
user_pref("mail.purge_threshold_migrated", true);
user_pref("mail.rights.version", 1);
user_pref("mail.root.imap", "/Users/isma/Library/Thunderbird/Profiles/vxz9nyiw.default-esr/ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.root.none", "/Users/isma/Library/Thunderbird/Profiles/vxz9nyiw.default-esr/Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.server.server1.ageLimit", 30);
user_pref("mail.server.server1.applyToFlaggedMessages", false);
user_pref("mail.server.server1.authMethod", 10);
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.cleanupBodies", false);
user_pref("mail.server.server1.clientid", "9665afb3-3668-4c28-9895-fc97785e63b7");
user_pref("mail.server.server1.daysToKeepBodies", 30);
user_pref("mail.server.server1.daysToKeepHdrs", 30);
user_pref("mail.server.server1.directory", "/Users/isma/Library/Thunderbird/Profiles/vxz9nyiw.default-esr/ImapMail/imap.gmail.com");
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/imap.gmail.com");
user_pref("mail.server.server1.downloadByDate", false);
user_pref("mail.server.server1.downloadUnreadOnly", false);
user_pref("mail.server.server1.hostname", "imap.gmail.com");
user_pref("mail.server.server1.is_gmail", true);
user_pref("mail.server.server1.lastFilterTime", 28787476);
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.max_cached_connections", 5);
user_pref("mail.server.server1.moveTargetMode", 1);
user_pref("mail.server.server1.name", "ijazappa@gmail.com");
user_pref("mail.server.server1.namespace.personal", "\"\"");
user_pref("mail.server.server1.nextFilterTime", 28787486);
user_pref("mail.server.server1.numHdrsToKeep", 2000);
user_pref("mail.server.server1.oauth2.issuer", "accounts.google.com");
user_pref("mail.server.server1.oauth2.scope", "https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar");
user_pref("mail.server.server1.port", 993);
user_pref("mail.server.server1.serverIDResponse", "(\"name\" \"GImap\" \"vendor\" \"Google, Inc.\" \"support-url\" \"https://support.google.com/mail\" \"version\" \"gmail.imap-server_20240919.07_p0\" \"remote-host\" \"46.25.233.125\")");
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.spamActionTargetAccount", "imap://ijazappa%40gmail.com@imap.gmail.com");
user_pref("mail.server.server1.spamActionTargetFolder", "imap://ijazappa%40gmail.com@imap.gmail.com/[Gmail]/Spam");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server1.timeout", 29);
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.userName", "ijazappa@gmail.com");
user_pref("mail.server.server2.ageLimit", 30);
user_pref("mail.server.server2.applyToFlaggedMessages", false);
user_pref("mail.server.server2.cleanupBodies", false);
user_pref("mail.server.server2.daysToKeepBodies", 30);
user_pref("mail.server.server2.daysToKeepHdrs", 30);
user_pref("mail.server.server2.directory", "/Users/isma/Library/Thunderbird/Profiles/vxz9nyiw.default-esr/Mail/Local Folders");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server2.downloadByDate", false);
user_pref("mail.server.server2.downloadUnreadOnly", false);
user_pref("mail.server.server2.hostname", "Local Folders");
user_pref("mail.server.server2.lastFilterTime", 28787476);
user_pref("mail.server.server2.name", "Carpetas locales");
user_pref("mail.server.server2.nextFilterTime", 28787486);
user_pref("mail.server.server2.numHdrsToKeep", 2000);
user_pref("mail.server.server2.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.userName", "nobody");
user_pref("mail.server.server3.ageLimit", 30);
user_pref("mail.server.server3.applyToFlaggedMessages", false);
user_pref("mail.server.server3.authMethod", 10);
user_pref("mail.server.server3.check_new_mail", true);
user_pref("mail.server.server3.cleanupBodies", false);
user_pref("mail.server.server3.clientid", "02d673ec-4d92-47d2-a580-864c253fa524");
user_pref("mail.server.server3.daysToKeepBodies", 30);
user_pref("mail.server.server3.daysToKeepHdrs", 30);
user_pref("mail.server.server3.directory", "/Users/isma/Library/Thunderbird/Profiles/vxz9nyiw.default-esr/ImapMail/imap.gmail-1.com");
user_pref("mail.server.server3.directory-rel", "[ProfD]ImapMail/imap.gmail-1.com");
user_pref("mail.server.server3.downloadByDate", false);
user_pref("mail.server.server3.downloadUnreadOnly", false);
user_pref("mail.server.server3.hostname", "imap.gmail.com");
user_pref("mail.server.server3.is_gmail", true);
user_pref("mail.server.server3.lastFilterTime", 28787479);
user_pref("mail.server.server3.login_at_startup", true);
user_pref("mail.server.server3.max_cached_connections", 5);
user_pref("mail.server.server3.name", "jajz1061@gmail.com");
user_pref("mail.server.server3.namespace.personal", "\"\"");
user_pref("mail.server.server3.nextFilterTime", 28787489);
user_pref("mail.server.server3.numHdrsToKeep", 2000);
user_pref("mail.server.server3.oauth2.issuer", "accounts.google.com");
user_pref("mail.server.server3.oauth2.scope", "https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar");
user_pref("mail.server.server3.port", 993);
user_pref("mail.server.server3.serverIDResponse", "(\"name\" \"GImap\" \"vendor\" \"Google, Inc.\" \"support-url\" \"https://support.google.com/mail\" \"version\" \"gmail.imap-server_20240919.07_p0\" \"remote-host\" \"46.25.233.125\")");
user_pref("mail.server.server3.socketType", 3);
user_pref("mail.server.server3.spamActionTargetAccount", "imap://jajz1061%40gmail.com@imap.gmail.com");
user_pref("mail.server.server3.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server3.timeout", 29);
user_pref("mail.server.server3.type", "imap");
user_pref("mail.server.server3.userName", "jajz1061@gmail.com");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.authMethod", 10);
user_pref("mail.smtpserver.smtp1.clientid", "212cdca8-bb2a-4537-a024-249b86dd446e");
user_pref("mail.smtpserver.smtp1.description", "Google Mail");
user_pref("mail.smtpserver.smtp1.hostname", "smtp.gmail.com");
user_pref("mail.smtpserver.smtp1.oauth2.issuer", "accounts.google.com");
user_pref("mail.smtpserver.smtp1.oauth2.scope", "https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.username", "ijazappa@gmail.com");
user_pref("mail.smtpserver.smtp2.authMethod", 10);
user_pref("mail.smtpserver.smtp2.clientid", "0ff52a5b-1f0e-4b2d-b832-10c6e456612c");
user_pref("mail.smtpserver.smtp2.description", "Google Mail");
user_pref("mail.smtpserver.smtp2.hostname", "smtp.gmail.com");
user_pref("mail.smtpserver.smtp2.oauth2.issuer", "accounts.google.com");
user_pref("mail.smtpserver.smtp2.oauth2.scope", "https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar");
user_pref("mail.smtpserver.smtp2.port", 465);
user_pref("mail.smtpserver.smtp2.try_ssl", 3);
user_pref("mail.smtpserver.smtp2.username", "jajz1061@gmail.com");
user_pref("mail.smtpservers", "smtp1,smtp2");
user_pref("mail.spam.version", 1);
user_pref("mail.spotlight.firstRunDone", true);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "087f81fe-2736-4e3a-9d1a-5446e0671be");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.15.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "pitopolla");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1727248368);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -20614);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1727268546);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1727268546);
user_pref("services.settings.thunderbird.search-config.last_check", 1727268546);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1727268546);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1726475307);
user_pref("svg.context-properties.content.enabled", true);
user_pref("toolkit.startup.last_success", 1727248269);
user_pref("toolkit.telemetry.cachedClientID", "d8a3e64f-81ee-4d67-abd7-8f2bafdac43a");
user_pref("toolkit.telemetry.previousBuildID", "20240903191356");
user_pref("mailnews.tags.$label1.color", "#e31414");
user_pref("mailnews.tags.$label1.tag", "1. SAF");
user_pref("mailnews.tags.$label2.color", "#ffa90a");
user_pref("mailnews.tags.$label2.tag", "2. AFL");
user_pref("mailnews.tags.$label3.color", "#74e617");
user_pref("mailnews.tags.$label3.tag", "3. MHM");
user_pref("mailnews.tags.$label4.color", "#2c64bf");
user_pref("mailnews.tags.$label4.tag", "4. DSV");
user_pref("mailnews.tags.$label5.color", "#7f36f5");
user_pref("mailnews.tags.$label5.tag", "5. FCL");
user_pref("mailnews.tags.prueba.color", "#008040");
user_pref("mailnews.tags.prueba.tag", "6. MTY");
user_pref("mailnews.tags.prueba.color", "#d042e3");
user_pref("mailnews.tags.prueba.tag", "7. LZP");

user_pref("mailnews.tags.$label1.color", "#e31414");
user_pref("mailnews.tags.$label1.tag", "1. SAF");
user_pref("mailnews.tags.$label2.color", "#ffa90a");
user_pref("mailnews.tags.$label2.tag", "2. AFL");
user_pref("mailnews.tags.$label3.color", "#74e617");
user_pref("mailnews.tags.$label3.tag", "3. MHM");
user_pref("mailnews.tags.$label4.color", "#2c64bf");
user_pref("mailnews.tags.$label4.tag", "4. DSV");
user_pref("mailnews.tags.$label5.color", "#7f36f5");
user_pref("mailnews.tags.$label5.tag", "5. FCL");
user_pref("mailnews.tags.prueba.color", "#008040");
user_pref("mailnews.tags.prueba.tag", "6. MTY");
user_pref("mailnews.tags.prueba.color", "#d042e3");
user_pref("mailnews.tags.prueba.tag", "7. LZP");

user_pref("mailnews.tags.$label1.color", "#e31414");
user_pref("mailnews.tags.$label1.tag", "1. SAF");
user_pref("mailnews.tags.$label2.color", "#ffa90a");
user_pref("mailnews.tags.$label2.tag", "2. AFL");
user_pref("mailnews.tags.$label3.color", "#74e617");
user_pref("mailnews.tags.$label3.tag", "3. MHM");
user_pref("mailnews.tags.$label4.color", "#2c64bf");
user_pref("mailnews.tags.$label4.tag", "4. DSV");
user_pref("mailnews.tags.$label5.color", "#7f36f5");
user_pref("mailnews.tags.$label5.tag", "5. FCL");
user_pref("mailnews.tags.prueba.color", "#008040");
user_pref("mailnews.tags.prueba.tag", "6. MTY");
user_pref("mailnews.tags.prueba.color", "#d042e3");
user_pref("mailnews.tags.prueba.tag", "7. LZP");

user_pref("mailnews.tags.$label1.color", "#e31414");
user_pref("mailnews.tags.$label1.tag", "1. SAF");
user_pref("mailnews.tags.$label2.color", "#ffa90a");
user_pref("mailnews.tags.$label2.tag", "2. AFL");
user_pref("mailnews.tags.$label3.color", "#74e617");
user_pref("mailnews.tags.$label3.tag", "3. MHM");
user_pref("mailnews.tags.$label4.color", "#2c64bf");
user_pref("mailnews.tags.$label4.tag", "4. DSV");
user_pref("mailnews.tags.$label5.color", "#7f36f5");
user_pref("mailnews.tags.$label5.tag", "5. FCL");
user_pref("mailnews.tags.prueba.color", "#008040");
user_pref("mailnews.tags.prueba.tag", "6. MTY");
user_pref("mailnews.tags.prueba.color", "#d042e3");
user_pref("mailnews.tags.prueba.tag", "7. LZP");

user_pref("mailnews.tags.$label1.color", "#e31414");
user_pref("mailnews.tags.$label1.tag", "1. SAF");
user_pref("mailnews.tags.$label2.color", "#ffa90a");
user_pref("mailnews.tags.$label2.tag", "2. AFL");
user_pref("mailnews.tags.$label3.color", "#74e617");
user_pref("mailnews.tags.$label3.tag", "3. MHM");
user_pref("mailnews.tags.$label4.color", "#2c64bf");
user_pref("mailnews.tags.$label4.tag", "4. DSV");
user_pref("mailnews.tags.$label5.color", "#7f36f5");
user_pref("mailnews.tags.$label5.tag", "5. FCL");
user_pref("mailnews.tags.prueba.color", "#008040");
user_pref("mailnews.tags.prueba.tag", "6. MTY");
user_pref("mailnews.tags.prueba.color", "#d042e3");
user_pref("mailnews.tags.prueba.tag", "7. LZP");
